## 用物件導向試做，建立屬於自己的normal scaler（標準化），包含fit及transform功能

### 先用sklearn跑一遍

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([ 0.5,  0.5])

In [15]:
scaler.var_

array([ 0.25,  0.25])

In [16]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [17]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

### 再來自己試試看囉

In [18]:
import numpy as np

In [19]:
class MyStandardScaler:
    def __init__(self): # 初始化定義
        self.mean = None
        self.var = None
        
        
    def fit(self, data):
        self.mean = np.mean(data, axis=0)
        self.var = np.var(data, axis=0)
        
    
    def transform(self, data):
        new_data = (np.array(data)-self.mean) / np.sqrt(self.var)
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [20]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [21]:
myscaler = MyStandardScaler()

In [22]:
myscaler.fit(data)

In [23]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [24]:
myscaler.transform([[2, 2]])

array([[ 3.,  3.]])