## 先用sklearn跑一遍

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [28]:
scaler = StandardScaler()

In [29]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
scaler.mean_

array([ 0.5,  0.5])

In [31]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [32]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

## 再來自己試試看囉

In [33]:
import numpy as np

In [34]:
class MyStandardScaler:
    def __init__(self):
        self.data_mean_ = None
        self.data_var_ = None
        self.data_std_ = None
        
    def fit(self, data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_var_ = np.var(data, axis=0)
        self.data_std_ = np.std(data, axis=0)
    
    def transform(self, data):
        new_data = (np.array(data)-self.data_mean_) / self.data_std_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [35]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [36]:
myscaler = MyStandardScaler()

In [37]:
myscaler.fit(data)

In [38]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [39]:
myscaler.transform([[2, 2]])

array([[ 3.,  3.]])